### ISSUE TITLE
When running the build for the TotalCross bytecode, we get exception if running on a headless mode

### ISSUE THREAD

**Issue by otavio** [TotalCross/totalcross#27]
The below exceptions is raised:

```
openjdk version "1.8.0_252-internal"
OpenJDK Runtime Environment (build 1.8.0_252-internal-ga)
OpenJDK 64-Bit Server VM (build 25.252-bga, mixed mode)
docker [build]$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)| Adding totalcross/res/spinner_iphone.gifException in thread "main" java.awt.AWTError: Toolkit not found: sun.awt.X11.XToolkit
|       at java.awt.Toolkit$2.run(Toolkit.java:867)
|       at java.awt.Toolkit$2.run(Toolkit.java:855)
|       at java.security.AccessController.doPrivileged(Native Method)
|       at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
|       at java.awt.Component.getToolkitImpl(Component.java:1226)
|       at java.awt.Component.getToolkit(Component.java:1214)
|       at java.awt.Component.checkImage(Component.java:3749)
|       at java.awt.ImageMediaEntry.getStatus(MediaTracker.java:951)
|       at java.awt.MediaTracker.statusAll(MediaTracker.java:480)
|       at java.awt.MediaTracker.waitForAll(MediaTracker.java:431)
|       at java.awt.MediaTracker.waitForAll(MediaTracker.java:401)
|       at totalcross.ui.image.Image$ImageLoader.<init>(Image.java:1802)
|       at totalcross.ui.image.Image.imageLoad(Image.java:1760)
|       at totalcross.ui.image.Image.imageParse(Image.java:1468)
|       at totalcross.ui.image.Image.<init>(Image.java:314)
|       at totalcross.ui.image.Image.<init>(Image.java:283)
|       at tc.tools.converter.J2TC.processFiles(J2TC.java:959)
|       at tc.tools.converter.J2TC.process(J2TC.java:1323)
|       at tc.Deploy.<init>(Deploy.java:85)
|       at tc.Deploy.main(Deploy.java:44)
| :deployTcui FAILED
```

It seems to come from:

https://github.com/TotalCross/totalcross/blob/develop/TotalCrossSDK/src/main/java/totalcross/ui/Spinner.java#L75

However, it seems that it is trying to load a spinner image even on headless mode.

Is it possible to be avoided?

**Comment by ItaloYeltsin** [comment]
It seems you are using a version of Java JDK8 that does not comes with the sun.* package required for convert all required images inside the project to png

**Comment by otavio** [comment]
@ItaloYeltsin if it is just a matter to convert them to PNG, this could be easily done.

**Comment by ItaloYeltsin** [comment]
Yeap, I've just edited my answer!

**Comment by otavio** [comment]
A very easy way to reproduce this error is using `openjdk-8-jdk-headless` as the runtime for the build process.

**Comment by ItaloYeltsin** [comment]
this is a little bit more complicated than we thought. Actually, the the reason why we make this conversion is to make an abstraction of gif inside a png. So, what happen is that we get all frames from gif file and put it them side by side in a .png file, so its possible to play the gif in the user side. We really need to keep this process.

On the other hand, we could add a library to do this instead of using the sun libraries.
