### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider

### ISSUE THREAD

**Issue by microhobby** [TotalCross/totalcross#34]
I am trying to compile the SDK and VM following this https://learn.totalcross.com/documentation/developers-area/how-to-build-totalcross-vm-wip

After compile with success I am trying to follow the documentation https://learn.totalcross.com/documentation/get-started/hello-world and execute the command "TotalCross: Package" for Linux target and I am getting the following fail: 

```
mvn package
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< br.com.microhobby:HelloWorld >--------------------
[INFO] Building HelloWorld 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ HelloWorld ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ HelloWorld ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- totalcross-maven-plugin:1.1:retrolambda (post-compile) @ HelloWorld ---
[INFO] Processing classes with Retrolambda
00:00  INFO: Bytecode version: 51 (Java 7)
00:00  INFO: Default methods:  false
00:00  INFO: Input directory:  /home/castello/tmp/tcc/HelloWorld/target/classes
00:00  INFO: Output directory: /home/castello/tmp/tcc/HelloWorld/target/classes
00:00  INFO: Classpath:        [/home/castello/tmp/tcc/HelloWorld/target/classes, /home/castello/.m2/repository/com/totalcross/totalcross-sdk/6.0.4/totalcross-sdk-6.0.4.jar, /home/castello/.m2/repository/com/googlecode/plist/dd-plist/1.19/dd-plist-1.19.jar, /home/castello/.m2/repository/org/xerial/sqlite-jdbc/3.8.7/sqlite-jdbc-3.8.7.jar, /home/castello/.m2/repository/de/schlichtherle/truezip/truezip-file/7.5.1/truezip-file-7.5.1.jar, /home/castello/.m2/repository/de/schlichtherle/truezip/truezip-kernel/7.5.1/truezip-kernel-7.5.1.jar, /home/castello/.m2/repository/de/schlichtherle/truezip/truezip-driver-zip/7.5.1/truezip-driver-zip-7.5.1.jar, /home/castello/.m2/repository/de/schlichtherle/truezip/truezip-swing/7.5.1/truezip-swing-7.5.1.jar, /home/castello/.m2/repository/org/apache/commons/commons-compress/1.3/commons-compress-1.3.jar, /home/castello/.m2/repository/commons-io/commons-io/2.2/commons-io-2.2.jar, /home/castello/.m2/repository/org/ow2/asm/asm/5.2/asm-5.2.jar, /home/castello/.m2/repository/org/ow2/asm/asm-tree/5.2/asm-tree-5.2.jar, /home/castello/.m2/repository/net/harawata/appdirs/1.0.0/appdirs-1.0.0.jar, /home/castello/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar, /home/castello/.m2/repository/net/coobird/thumbnailator/0.4.8/thumbnailator-0.4.8.jar, /home/castello/.m2/repository/com/totalcross/annotations/totalcross-annotations/1.0.0/totalcross-annotations-1.0.0.jar, /home/castello/.m2/repository/net/java/dev/jna/jna-platform/4.2.2/jna-platform-4.2.2.jar, /home/castello/.m2/repository/net/java/dev/jna/jna/4.2.2/jna-4.2.2.jar, /home/castello/.m2/repository/org/vafer/jdeb/0.7/jdeb-0.7.jar, /home/castello/.m2/repository/org/apache/maven/maven-plugin-api/2.0.5/maven-plugin-api-2.0.5.jar, /home/castello/.m2/repository/org/apache/maven/maven-project/2.0.5/maven-project-2.0.5.jar, /home/castello/.m2/repository/org/apache/maven/maven-settings/2.0.5/maven-settings-2.0.5.jar, /home/castello/.m2/repository/org/apache/maven/maven-profile/2.0.5/maven-profile-2.0.5.jar, /home/castello/.m2/repository/org/apache/maven/maven-model/2.0.5/maven-model-2.0.5.jar, /home/castello/.m2/repository/org/apache/maven/maven-artifact-manager/2.0.5/maven-artifact-manager-2.0.5.jar, /home/castello/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.5/maven-repository-metadata-2.0.5.jar, /home/castello/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-2/wagon-provider-api-1.0-beta-2.jar, /home/castello/.m2/repository/org/codehaus/plexus/plexus-container-default/1.0-alpha-9/plexus-container-default-1.0-alpha-9.jar, /home/castello/.m2/repository/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar, /home/castello/.m2/repository/org/apache/maven/maven-artifact/2.0.5/maven-artifact-2.0.5.jar, /home/castello/.m2/repository/org/codehaus/plexus/plexus-utils/1.4.1/plexus-utils-1.4.1.jar, /home/castello/.m2/repository/org/apache/ant/ant/1.7.1/ant-1.7.1.jar, /home/castello/.m2/repository/org/apache/ant/ant-launcher/1.7.1/ant-launcher-1.7.1.jar, /home/castello/.m2/repository/junit/junit/3.8.2/junit-3.8.2.jar, /home/castello/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.56/bcpkix-jdk15on-1.56.jar, /home/castello/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.56/bcprov-jdk15on-1.56.jar]
00:00  INFO: Included files:   all
00:00  INFO: Agent enabled:    false
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ HelloWorld ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/castello/tmp/tcc/HelloWorld/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ HelloWorld ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ HelloWorld ---
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ HelloWorld ---
[INFO] Building jar: /home/castello/tmp/tcc/HelloWorld/target/HelloWorld.jar
[INFO] 
[INFO] --- totalcross-maven-plugin:1.1:package (post-package) @ HelloWorld ---
Number of dependencies: 3
Command line: /home/castello/tmp/tcc/HelloWorld/target/HelloWorld.jar -linux /n HelloWorld /p /r 5443444B5AAEEB90306B00E4 
TotalCross SDK version 6.0.4.0 running on linux with JDK 1.8
Current folder: /home/castello/tmp/tcc/HelloWorld
Etc directory: /home/castello/tmp/TotalCross/TotalCrossSDK/etc/
Classpath: /home/castello/.m2/repository/com/totalcross/totalcross-sdk/6.0.4/totalcross-sdk-6.0.4.jar
Creating single installation package
The application was signed with the given registration key.
Next SDK expiration date: 1 June, 2020
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
        at tc.Deploy.<init>(Deploy.java:89)
        at tc.Deploy.main(Deploy.java:51)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 2 more

** (process:146789): WARNING **: 00:59:39.571: JNI_OnUnload() called but this is not supported yet

[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo (MojoExecutor.java:119)
    at com.totalcross.TotalCrossMojo.deploy (TotalCrossMojo.java:134)
    at com.totalcross.TotalCrossMojo.execute (TotalCrossMojo.java:63)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.157 s
[INFO] Finished at: 2020-05-25T00:59:39-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.totalcross:totalcross-maven-plugin:1.1:package (post-package) on project HelloWorld: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Let me know if I can help with any other information, thanks

**Comment by brunoamuniz** [comment]
hey @microhobby, you need to copy to your main folder:
1. The folder "etc"
2. The LitebaseLib.tcz

If you are using the VSCode plugin or CLI integration, you will find this folders/files in the TotalCross folder in your user folder.

This files contain some dependencies required to build the app.

Thanks for the issue, we will revise the docs too.

Cheers

**Comment by microhobby** [comment]
Hi @brunoamuniz ,

thanks, copying the `etc` folder and the LitebaseLib.tcz` works!
